baseurl: ''
exclude: ['README.md']
permalink: pretty
title: '见声科技'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/aiHearingMobile.png"
  desktop: "images/logo/aiHearing.png"
  desktop_height: "60px"
footer:
  copyright_text: '晋公网安备14019202000640号, 晋ICP备18009349号-1, 见声科技 by <a class="zerostatic" href="https://hypech.com">hypech.com</a>'

seo:
  meta_og_title: "看见声音"
  meta_og_type: "website"
  meta_og_url: "https://aihearing.github.io"
  meta_og_image: "https://raw.githubusercontent.com/zerostaticthemes/jekyll-serif-theme/master/screenshots/tn.png"
  meta_og_description: "3 minutes hearing test."
  meta_twitter_card: "summary"
  meta_twitter_site: "@aihearing"
  meta_twitter_creator: "@aihearing"

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
